[workspace]
channels = [
    "https://prefix.dev/conda-forge",
]
platforms = ["linux-64", "osx-64"]


[dependencies]
matplotlib-base = ">=3.10.8,<4"
numpy = ">=2.3.5,<3"
numba = ">=0.62.1,<0.63"
scikit-learn = ">=1.7.2,<2"
scipy = ">=1.16.3,<2"
numexpr = ">=2.14.1,<3"
pytables = ">=3.10.2,<4"
h5py = ">=3.15.1,<4"
colorcet = ">=3.1.0,<4"
bottleneck = ">=1.6.0,<2"
psutil = ">=7.1.3,<8"
rtree = ">=1.4.1,<2"


[pypi-dependencies]
json-with-comments = ">=1.2.10, <2"

lardon={path='.', editable = true }

[feature.local.dependencies]
xrootd = "*"
iminuit = "*"
bokeh = "*"
ipython = "*"
fast-histogram = "*"
uproot = "*"
vitables = "*"


[feature.test.dependencies]
pytest = ">=9,<10"
pytest-cov = ">=7,<8"

[feature.test.tasks.test]
cmd = "pytest"

[feature.dev.dependencies]
ruff = ">=0.14,<0.15"
#build = "*"

[feature.dev.pypi-dependencies]
build = "*"

[feature.dev.tasks]
format = "ruff format"
check = "ruff check"



[environments]
prod = { solve-group = "prod" }
test = { features = ["test"], solve-group = "prod" }
default = { features = ["local", "dev", "test"], solve-group = "prod" }
